// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parser.Migrations
{
    [DbContext(typeof(ItemDb))]
    partial class ItemDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Parser.Models.ItemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("CurrentPrice")
                        .HasColumnType("double");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemListId")
                        .HasColumnType("int");

                    b.Property<string>("Trend")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)");

                    b.Property<double>("TrendValue")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ItemListId");

                    b.ToTable("ItemHistory");
                });

            modelBuilder.Entity("Parser.Models.ItemIcon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("ImageIcon")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("VARCHAR(90)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("ItemIcons");
                });

            modelBuilder.Entity("Parser.Models.ItemList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)");

                    b.HasKey("Id");

                    b.ToTable("ItemList");
                });

            modelBuilder.Entity("Parser.Models.ItemData", b =>
                {
                    b.HasOne("Parser.Models.ItemList", "ItemList")
                        .WithMany("ItemData")
                        .HasForeignKey("ItemListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemList");
                });

            modelBuilder.Entity("Parser.Models.ItemIcon", b =>
                {
                    b.HasOne("Parser.Models.ItemList", "Item")
                        .WithOne("Icon")
                        .HasForeignKey("Parser.Models.ItemIcon", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Parser.Models.ItemList", b =>
                {
                    b.Navigation("Icon");

                    b.Navigation("ItemData");
                });
#pragma warning restore 612, 618
        }
    }
}
